# Getting Started with pandas

In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

## Introduction to pandas Data Structures

### Series

In [4]:
obj = Series([4,7,-3,5])

In [5]:
obj

0    4
1    7
2   -3
3    5
dtype: int64

In [6]:
obj.values

array([ 4,  7, -3,  5])

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = Series([4,7,-5,3], index=['d','a','b','c'])

In [9]:
obj2

d    4
a    7
b   -5
c    3
dtype: int64

In [10]:
obj2.index

Index([u'd', u'a', u'b', u'c'], dtype='object')

In [11]:
obj2['a']

7

In [12]:
obj2['b'] = 6

In [13]:
obj2

d    4
a    7
b    6
c    3
dtype: int64

In [14]:
obj2[obj2 > 0]

d    4
a    7
b    6
c    3
dtype: int64

In [15]:
obj2 * 2

d     8
a    14
b    12
c     6
dtype: int64

In [16]:
obj2

d    4
a    7
b    6
c    3
dtype: int64

In [20]:
np.exp(obj2)

d      54.598150
a    1096.633158
b     403.428793
c      20.085537
dtype: float64

In [21]:
'b' in obj2

True

In [22]:
'e' in obj2

False

In [23]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}

In [24]:
obj3 = Series(sdata)

In [25]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [26]:
states = ['California', 'Ohio', 'Oregon','Texas']

In [28]:
obj4 = Series(sdata, index = states)

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [33]:
obj4.name = 'population'

In [34]:
obj4.index.name = 'state'

In [35]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [36]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [37]:
obj

Bob      4
Steve    7
Jeff    -3
Ryan     5
dtype: int64

### DataFrame

In [40]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],
        'year': [2000,2001,2002,2001,2002],
        'pop': [1.5,1.7,3.6,2.4,2.9]}
frame = DataFrame(data)

In [41]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [42]:
DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [43]:
frame2 = DataFrame(data, columns=['year','state','pop','debt'], index=['one','two','three','four','five'])

In [44]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [45]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [46]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [47]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [53]:
frame2.ix['three']

/Users/ChrisBarnes/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [54]:
frame2['debt'] = 16.5

In [55]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [56]:
frame2['debt'] = np.arange(5.)

In [57]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [58]:
val = Series([-1.2, -1.5, -1.7], index = ['two','four','five'])

In [59]:
frame2['debt'] = val

In [60]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [62]:
frame2['eastern'] = frame2.state == 'Ohio'

In [63]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [64]:
del frame2['eastern']

In [65]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [66]:
pop = {'Nevada': {2001:2.4,2002:2.9},
       'Ohio': {2000:1.5, 2001: 1.7, 2002: 3.6}}

In [67]:
frame3 = DataFrame(pop)

In [68]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [69]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [70]:
DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [71]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [72]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [73]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [74]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [75]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [76]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

### Index Objects

In [77]:
obj = Series(range(3), index=['a','b','c'])

In [78]:
index = obj.index

In [79]:
index

Index([u'a', u'b', u'c'], dtype='object')

In [80]:
index[1:]

Index([u'b', u'c'], dtype='object')

In [81]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [82]:
index = pd.Index(np.arange(3))

In [83]:
obj2 = Series([1.5,2.5,0], index = index)

In [84]:
obj2.index is index

True

In [85]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [86]:
'Ohio' in frame3.columns

True

In [87]:
2003 in frame3.index

False

## Essential Functionality

### Reindexing

In [88]:
obj = Series([4.5,7.2,-5.3,3.6], index = ['a','b','c','d'])

In [89]:
obj

a    4.5
b    7.2
c   -5.3
d    3.6
dtype: float64

In [90]:
ojb2 = obj.reindex(['a','d','b','c','e'])

In [91]:
obj2

0    1.5
1    2.5
2    0.0
dtype: float64

In [92]:
obj.reindex(['a','b','c','d','e'], fill_value = 0)

a    4.5
b    7.2
c   -5.3
d    3.6
e    0.0
dtype: float64

In [96]:
obj3 = Series(['blue','purple','yellow'], index=[0,2,4])

In [97]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [101]:
frame = DataFrame(np.arange(9).reshape((3,3)), index=['a','c','d'],
                  columns = ['Ohio', 'Texas','California'])

In [99]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [102]:
frame2 = frame.reindex(['a','b','c','d'])

In [103]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [104]:
states = ['Texas','Utah','California']

In [105]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [106]:
frame.reindex(index=['a','b','c','d'], method = 'ffill', columns = states)

ValueError: index must be monotonic increasing or decreasing

In [108]:
frame.loc[['a','b','c','d'], states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

### Dropping entries from an axis

In [109]:
obj = Series(np.arange(5.), index=['a','b','c','d','e'])

In [110]:
new_obj = obj.drop('c')

In [111]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [112]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [113]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [115]:
data = DataFrame(np.arange(16).reshape((4,4)),
                 index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns = ['one', 'two', 'three', 'four'])

In [116]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [117]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [118]:
data.drop(['two','four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### Indexing, selection, and filtering

In [3]:
obj = Series(np.arange(4.), index=['a','b','c','d'])

In [4]:
obj['b']

1.0

In [5]:
obj[1]

1.0

In [6]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [7]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [8]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [9]:
obj[obj>2]

d    3.0
dtype: float64

In [10]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [11]:
obj['b':'c'] = 5

In [12]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [14]:
data = DataFrame(np.arange(16).reshape((4,4)), 
                 index = ['Ohio','Colorado','Utah','New York'],
                 columns = ['one','two','three','four'])

In [15]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [16]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [17]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [18]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [19]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [20]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [23]:
data[data <5] = 0

In [24]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [25]:
data.ix['Colorado',['two','three']]

/Users/ChrisBarnes/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


two      5
three    6
Name: Colorado, dtype: int64

In [26]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [30]:
data.iloc[['Colorado','Utah'],[3,0,1]]

TypeError: cannot perform reduce with flexible type

In [29]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [31]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [33]:
data.iloc[data.three>5,:3]

ValueError: iLocation based boolean indexing cannot use an indexable as a mask

## Arithmetic and data alignment

In [34]:
s1 = Series([7.3,-2.5,3.4,1.5], index=['a','c','d','e'])

In [35]:
s2 = Series([-2.1,3.6,-1.5,4,3.1], index=['a','c','e','f','g'])

In [36]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [37]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [38]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [39]:
df1 = DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'),
                index=['Ohio','Texas','Colorado'])

In [40]:
df2 = DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'),
                index=['Utah','Ohio','Texas','Oregon'])

In [41]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [42]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [43]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### Arithmetic methods with fill values

In [44]:
df1 = DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))

In [45]:
df2 = DataFrame(np.arange(20.).reshape((4,5)), columns = list('abcde'))

In [46]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [47]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [48]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [49]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [50]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### Operations between DataFrame and Series

In [51]:
arr = np.arange(12.).reshape((3,4))

In [52]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [53]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [55]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [60]:
frame = DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'), index = ['Utah','Ohio','Texas','Oregon'])

In [61]:
series = frame.iloc[0]

In [62]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [63]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [64]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [65]:
series2 = Series(range(3), index=['b','e','f'])

In [66]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [67]:
series3 = frame['d']

In [68]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [69]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## Function application and mapping

In [70]:
frame = DataFrame(np.random.randn(4,3), columns=list('bde'), index=['Utah','Ohio','Texas','Oregon'])

In [71]:
np.abs(frame)

b         d         e
Utah    1.158523  0.596066  0.078676
Ohio    1.339470  1.043537  0.265514
Texas   0.722159  0.048331  0.262379
Oregon  0.153895  0.559508  0.525469

In [72]:
frame

b         d         e
Utah    1.158523  0.596066  0.078676
Ohio   -1.339470 -1.043537 -0.265514
Texas   0.722159  0.048331 -0.262379
Oregon  0.153895 -0.559508  0.525469

In [73]:
f = lambda x: x.max() - x.min()

In [74]:
frame.apply(f)

b    2.497993
d    1.639603
e    0.790983
dtype: float64

In [75]:
frame.apply(f, axis=1)

Utah      1.079847
Ohio      1.073956
Texas     0.984538
Oregon    1.084977
dtype: float64

In [76]:
def f(x):
    return Series([x.min(), x.max()], index=['min', 'max'])

In [78]:
frame.apply(f)

b         d         e
min -1.339470 -1.043537 -0.265514
max  1.158523  0.596066  0.525469

In [79]:
format = lambda x: '%.2f' % x

In [80]:
frame.applymap(format)

b      d      e
Utah     1.16   0.60   0.08
Ohio    -1.34  -1.04  -0.27
Texas    0.72   0.05  -0.26
Oregon   0.15  -0.56   0.53

In [81]:
frame['e'].map(format)

Utah       0.08
Ohio      -0.27
Texas     -0.26
Oregon     0.53
Name: e, dtype: object


### Sorting and ranking

In [82]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [84]:
obj = Series(range(4), index=['d','a','b','c'])

In [85]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [86]:
frame = DataFrame(np.arange(8).reshape((2,4)), index=['three','one'], columns=['d','a','b','c'])

In [87]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [88]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [89]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [90]:
obj = Series([4,7,-3,2])

In [92]:
obj.order()

AttributeError: 'Series' object has no attribute 'order'

In [93]:
obj = Series([4,np.nan,7,np.nan,-3,2])

In [94]:
obj.order()

AttributeError: 'Series' object has no attribute 'order'

In [95]:
frame = DataFrame({'b':[4,7,-3,2], 'a': [0,1,0,1]})

In [96]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [97]:
frame.sort_index(by='b')

/Users/ChrisBarnes/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  """Entry point for launching an IPython kernel.


a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [99]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [100]:
frame.sort_values(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [101]:
obj = Series([7,-5,7,4,2,0,4])

In [102]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [103]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [104]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

#### Axis indexes with duplicate values

In [105]:
obj = Series(range(5), index=['a','a','b','b','c'])

In [106]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [108]:
obj.index.is_unique

False

In [109]:
obj['a']

a    0
a    1
dtype: int64

In [110]:
obj['c']

4

In [111]:
df = DataFrame(np.random.randn(4,3), index=['a','a','b','b'])

In [112]:
df

0         1         2
a  0.501268  0.892956 -0.539112
a  0.788366  0.056754 -0.494422
b  0.571742 -1.664834  2.219382
b -0.010213  0.612560  1.030560

In [114]:
df.loc['a']

0         1         2
a  0.501268  0.892956 -0.539112
a  0.788366  0.056754 -0.494422

## Summarizing and Computing Descriptive Statistics

In [115]:
df = DataFrame([[1.4, np.nan], [7.1,-4.5], [np.nan,np.nan], [0.75,-1.3]], index=['a','b','c','d'], columns = ['one','two'])

In [116]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [117]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [118]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [119]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [121]:
df.idxmax()

one    b
two    d
dtype: object

In [122]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [123]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [126]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

### Correlation and Covariance

In [3]:
from pandas_datareader import data as web

In [4]:
all_data = {}

In [6]:
for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']:
    all_data[ticker] = web.get_data_google(ticker)

/Users/ChrisBarnes/anaconda/lib/python2.7/site-packages/pandas_datareader/google/daily.py:40: UnstableAPIWarning: 
The Google Finance API has not been stable since late 2017. Requests seem
to fail at random. Failure is especially common when bulk downloading.

  warnings.warn(UNSTABLE_WARNING, UnstableAPIWarning)


In [7]:
all_data

{'AAPL':               Open    High     Low   Close     Volume
 Date                                                 
 2010-01-04   30.49   30.64   30.34   30.57  123432050
 2010-01-05   30.66   30.80   30.46   30.63  150476004
 2010-01-06   30.63   30.75   30.11   30.14  138039594
 2010-01-07   30.25   30.29   29.86   30.08  119282324
 2010-01-08   30.04   30.29   29.87   30.28  111969081
 2010-01-11   30.40   30.43   29.78   30.02  115557365
 2010-01-12   29.88   29.97   29.49   29.67  148614774
 2010-01-13   29.70   30.13   29.16   30.09  151472335
 2010-01-14   30.02   30.07   29.86   29.92  108288411
 2010-01-15   30.13   30.23   29.41   29.42  148584065
 2010-01-19   29.76   30.74   29.61   30.72  182501620
 2010-01-20   30.70   30.79   29.93   30.25  153037892
 2010-01-21   30.30   30.47   29.60   29.72  152038565
 2010-01-22   29.54   29.64   28.17   28.25  220441872
 2010-01-25   28.93   29.24   28.60   29.01  266424802
 2010-01-26   29.42   30.53   28.94   29.42  466777486
 2

In [10]:
price = DataFrame({tic: data['Close'] for tic,data in all_data.iteritems()})

In [12]:
volume = DataFrame({tic: data['Volume'] for tic,data in all_data.iteritems()})

In [13]:
volume

AAPL       GOOG       IBM         MSFT
Date                                                     
2010-01-04  123432050.0        NaN   6155846   38414185.0
2010-01-05  150476004.0        NaN   6842471   49758862.0
2010-01-06  138039594.0        NaN   5605290   58182332.0
2010-01-07  119282324.0        NaN   5840569   50564285.0
2010-01-08  111969081.0        NaN   4197105   51201289.0
2010-01-11  115557365.0        NaN   5731177   68754648.0
2010-01-12  148614774.0        NaN   8083354   65913228.0
2010-01-13  151472335.0        NaN   6458302   51863463.0
2010-01-14  108288411.0        NaN   7114544   63244767.0
2010-01-15  148584065.0        NaN   8502320   79915648.0
2010-01-19  182501620.0        NaN  13916168   46582886.0
2010-01-20  153037892.0        NaN  15201857   54857712.0
2010-01-21  152038565.0        NaN   9608696   73086701.0
2010-01-22  220441872.0        NaN  10089325  102004573.0
2010-01-25  266424802.0        NaN   5738920   63381173.0
2010-01-26  466777486.0        NaN   7136640   66647676.0
2010-01-27  430642030.0        NaN   8719447   63949492.0
2010-01-28  293375376.0        NaN   9622829  117513692.0
2010-01-29  311487785.0        NaN  11572387  193888424.0
2010-02-01  187468421.0        NaN   7249873   85931099.0
2010-02-02  174585313.0        NaN   5900187   54413654.0
2010-02-03  153831769.0        NaN   4177981   61397848.0
2010-02-04  189412762.0        NaN   9129991   77849968.0
2010-02-05  212576350.0        NaN   8618019   80960063.0
2010-02-08  119567119.0        NaN   5719389   52826474.0
2010-02-09  158221028.0        NaN   6044966   59195742.0
2010-02-10   92590218.0        NaN   5219260   48591246.0
2010-02-11  137585903.0        NaN   5091096   65995913.0
2010-02-12  163866906.0        NaN   8018236   81121515.0
2010-02-16  135987761.0        NaN   6777265   51938098.0
...                 ...        ...       ...          ...
2018-01-05   23660018.0  1279123.0   5195764   23407110.0
2018-01-08   20567766.0  1047603.0   5237523   22113049.0
2018-01-09   21583997.0   902541.0   4341810   19484317.0
2018-01-10   23959895.0  1042793.0   4174105   18652201.0
2018-01-11   18667729.0   978292.0   3794453   17808877.0
2018-01-12   25418080.0  1720533.0   5031886   24271531.0
2018-01-16   29565947.0  1575261.0   7794195   36599736.0
2018-01-17   34386836.0  1202639.0  11710033   25621164.0
2018-01-18   31193352.0  1198234.0  14259345   24159683.0
2018-01-19   32425067.0  1778229.0  21172488   36875013.0
2018-01-22   27108551.0  1617975.0   8480795   23601555.0
2018-01-23   32689146.0  1333056.0   7466232   23412841.0
2018-01-24   51105090.0  1416625.0   5645003   33277483.0
2018-01-25   41529004.0  1480540.0   3302520   26383238.0
2018-01-26   39143011.0  2018755.0   3787913   29172167.0
2018-01-29   50640406.0  1378913.0   3516995   31569940.0
2018-01-30   46048185.0  1556346.0   4902341   38635053.0
2018-01-31   32478930.0  1538688.0   4072830   48756338.0
2018-02-01   47230787.0  2412114.0   4434242   47227882.0
2018-02-02   86593825.0  4857943.0   5251938   47867753.0
2018-02-05   72738522.0  3798301.0   8746599   51031465.0
2018-02-06   68243838.0  3447956.0   9867678   67998564.0
2018-02-07   51608580.0  2369232.0   6149207   41107592.0
2018-02-08   54390516.0  2859136.0   6779095   55628657.0
2018-02-09   70672608.0  3505862.0   7828290   63499065.0
2018-02-12   60819539.0  2057718.0   5881377   35720341.0
2018-02-13   32549163.0  1265054.0   4891010   26407702.0
2018-02-14   40644933.0  1555787.0   5479033   34960912.0
2018-02-15   51147171.0  1843442.0   5623581   27823866.0
2018-02-16   40176091.0  1681612.0   4282908   30596919.0

[2046 rows x 4 columns]

In [14]:
returns = price.pct_change()

In [15]:
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2018-02-12  0.040279  0.013645  0.012641  0.010773
2018-02-13  0.010018  0.000152 -0.004293  0.007854
2018-02-14  0.018437  0.016728  0.026600  0.010909
2018-02-15  0.033578  0.018529  0.008077  0.020372
2018-02-16 -0.003237  0.004846  0.001090 -0.007123

In [16]:
returns.MSFT.corr(returns.IBM)

0.47288862919847008

In [17]:
returns.MSFT.cov(returns.IBM)

7.9991486081478589e-05

In [18]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.423606  0.360890  0.400711
GOOG  0.423606  1.000000  0.389194  0.490314
IBM   0.360890  0.389194  1.000000  0.472889
MSFT  0.400711  0.490314  0.472889  1.000000

In [19]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000256  0.000103  0.000069  0.000091
GOOG  0.000103  0.000231  0.000071  0.000105
IBM   0.000069  0.000071  0.000143  0.000080
MSFT  0.000091  0.000105  0.000080  0.000200

In [20]:
returns.corrwith(returns.IBM)

AAPL    0.360890
GOOG    0.389194
IBM     1.000000
MSFT    0.472889
dtype: float64

In [21]:
returns.corrwith(volume)

AAPL   -0.067782
GOOG    0.011249
IBM    -0.159014
MSFT   -0.086683
dtype: float64

### Unique Values, Value Counts, and Membership

In [22]:
obj = Series(['a','c','d','a','a','b','b','c','c'])

In [23]:
uniques = obj.unique()

In [24]:
uniques

array(['a', 'c', 'd', 'b'], dtype=object)

In [25]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [26]:
mask = obj.isin(['b','c'])

In [27]:
mask

0    False
1     True
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [28]:
obj[mask]

1    c
5    b
6    b
7    c
8    c
dtype: object

In [29]:
data = DataFrame({'Qu1': [1,3,4,3,4],
                  'Qu2': [2,3,1,2,3],
                  'Qu3': [1,5,2,4,4]})

In [30]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [31]:
result = data.apply(pd.value_counts).fillna(0)

In [32]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

## Handling Missing Data