# Getting Started with pandas

In [19]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

## Introduction to pandas Data Structures

### Series

In [4]:
obj = Series([4,7,-3,5])

In [5]:
obj

0    4
1    7
2   -3
3    5
dtype: int64

In [6]:
obj.values

array([ 4,  7, -3,  5])

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = Series([4,7,-5,3], index=['d','a','b','c'])

In [9]:
obj2

d    4
a    7
b   -5
c    3
dtype: int64

In [10]:
obj2.index

Index([u'd', u'a', u'b', u'c'], dtype='object')

In [11]:
obj2['a']

7

In [12]:
obj2['b'] = 6

In [13]:
obj2

d    4
a    7
b    6
c    3
dtype: int64

In [14]:
obj2[obj2 > 0]

d    4
a    7
b    6
c    3
dtype: int64

In [15]:
obj2 * 2

d     8
a    14
b    12
c     6
dtype: int64

In [16]:
obj2

d    4
a    7
b    6
c    3
dtype: int64

In [20]:
np.exp(obj2)

d      54.598150
a    1096.633158
b     403.428793
c      20.085537
dtype: float64

In [21]:
'b' in obj2

True

In [22]:
'e' in obj2

False

In [23]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}

In [24]:
obj3 = Series(sdata)

In [25]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [26]:
states = ['California', 'Ohio', 'Oregon','Texas']

In [28]:
obj4 = Series(sdata, index = states)

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [33]:
obj4.name = 'population'

In [34]:
obj4.index.name = 'state'

In [35]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [36]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [37]:
obj

Bob      4
Steve    7
Jeff    -3
Ryan     5
dtype: int64

### DataFrame

In [40]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],
        'year': [2000,2001,2002,2001,2002],
        'pop': [1.5,1.7,3.6,2.4,2.9]}
frame = DataFrame(data)

In [41]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [42]:
DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [43]:
frame2 = DataFrame(data, columns=['year','state','pop','debt'], index=['one','two','three','four','five'])

In [44]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [45]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [46]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [47]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [53]:
frame2.ix['three']

/Users/ChrisBarnes/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [54]:
frame2['debt'] = 16.5

In [55]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [56]:
frame2['debt'] = np.arange(5.)

In [57]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [58]:
val = Series([-1.2, -1.5, -1.7], index = ['two','four','five'])

In [59]:
frame2['debt'] = val

In [60]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [62]:
frame2['eastern'] = frame2.state == 'Ohio'

In [63]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [64]:
del frame2['eastern']

In [65]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [66]:
pop = {'Nevada': {2001:2.4,2002:2.9},
       'Ohio': {2000:1.5, 2001: 1.7, 2002: 3.6}}

In [67]:
frame3 = DataFrame(pop)

In [68]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [69]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [70]:
DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [71]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [72]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [73]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [74]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [75]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [76]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

### Index Objects

In [77]:
obj = Series(range(3), index=['a','b','c'])

In [78]:
index = obj.index

In [79]:
index

Index([u'a', u'b', u'c'], dtype='object')

In [80]:
index[1:]

Index([u'b', u'c'], dtype='object')

In [81]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [82]:
index = pd.Index(np.arange(3))

In [83]:
obj2 = Series([1.5,2.5,0], index = index)

In [84]:
obj2.index is index

True

In [85]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [86]:
'Ohio' in frame3.columns

True

In [87]:
2003 in frame3.index

False

## Essential Functionality

### Reindexing

In [88]:
obj = Series([4.5,7.2,-5.3,3.6], index = ['a','b','c','d'])

In [89]:
obj

a    4.5
b    7.2
c   -5.3
d    3.6
dtype: float64

In [90]:
ojb2 = obj.reindex(['a','d','b','c','e'])

In [91]:
obj2

0    1.5
1    2.5
2    0.0
dtype: float64

In [92]:
obj.reindex(['a','b','c','d','e'], fill_value = 0)

a    4.5
b    7.2
c   -5.3
d    3.6
e    0.0
dtype: float64

In [96]:
obj3 = Series(['blue','purple','yellow'], index=[0,2,4])

In [97]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [101]:
frame = DataFrame(np.arange(9).reshape((3,3)), index=['a','c','d'],
                  columns = ['Ohio', 'Texas','California'])

In [99]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [102]:
frame2 = frame.reindex(['a','b','c','d'])

In [103]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [104]:
states = ['Texas','Utah','California']

In [105]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [106]:
frame.reindex(index=['a','b','c','d'], method = 'ffill', columns = states)

ValueError: index must be monotonic increasing or decreasing

In [108]:
frame.loc[['a','b','c','d'], states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

### Dropping entries from an axis

In [109]:
obj = Series(np.arange(5.), index=['a','b','c','d','e'])

In [110]:
new_obj = obj.drop('c')

In [111]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [112]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [113]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [115]:
data = DataFrame(np.arange(16).reshape((4,4)),
                 index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns = ['one', 'two', 'three', 'four'])

In [116]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [117]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [118]:
data.drop(['two','four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### Indexing, selection, and filtering